var grupos = {
    "group": [
        {
         "id" : "A",
         "match":[
            {
                "id":"1",
                "date":"2014-06-12T17:00:00-03:00",
                "place":"Sao Paulo",
                "team_left":"Brasil",
		"team_right":"Croacia"
            },
            {
                "id":"2",
                "date":"2014-06-13T13:00:00-03:00",
                "place":"Natal",
                "team_left":"Mexico",
		"team_right":"Camerun"
            },
            {
                "id":"3",
                "date":"2014-06-17T16:00:00-03:00",
                "place":"Fortaleza",
                "team_left":"Brasil",
		"team_right":"Mexico"
            },
            {
                "id":"4",
                "date":"2014-06-18T16:00:00-03:00",
                "place":"Manaos",
                "team_left":"Camerun",
		"team_right":"Croacia"
            },
            {
                "id":"5",
                "date":"2014-06-23T17:00:00-03:00",
                "place":"Brasilia",
                "team_left":"Camerun",
		"team_right":"Brasil"
            },
            {
                "id":"6",
                "date":"2014-06-23T17:00:00-03:00",
                "place":"Recife",
                "team_left":"Croacia",
		"team_right":"Mexico"
            }     				
         ]
        },
        {
         "id" : "B",
         "match":[
            {
                "id":"1",
                "date":"2014-06-13T16:00:00-03:00",
                "place":"Bahia",
                "team_left":"España",
		"team_right":"Holanda"
            },
            {
                "id":"2",
                "date":"2014-06-13T19:00:00-03:00",
                "place":"Cuiaba",
                "team_left":"Chile",
		"team_right":"Australia"
            },
            {
                "id":"3",
                "date":"2014-06-18T13:00:00-03:00",
                "place":"Porto Alegre",
                "team_left":"Australia",
		"team_right":"Holanda"
            },
            {
                "id":"4",
                "date":"2014-06-18T19:00:00-03:00",
                "place":"Rio de Janeiro",
                "team_left":"España",
		"team_right":"Chile"
            },
            {
                "id":"5",
                "date":"2014-06-23T13:00:00-03:00",
                "place":"Curitiba",
                "team_left":"Australia",
		"team_right":"España"
            },
            {
                "id":"6",
                "date":"2014-06-23T13:00:00-03:00",
                "place":"Sao Paulo",
                "team_left":"Holanda",
		"team_right":"Chile"
            }     				
         ]
        },
       {
         "id" : "C",
         "match":[
            {
                "id":"1",
                "date":"2014-06-15T13:00:00-03:00",
                "place":"Belo Horizonte",
                "team_left":"Colombia",
		"team_right":"Grecia"
            },
            {
                "id":"2",
                "date":"2014-06-14T22:00:00-03:00",
                "place":"Recife",
                "team_left":"Costa de Marfil",
		"team_right":"Japon"
            },
            {
                "id":"3",
                "date":"2014-06-19T13:00:00-03:00",
                "place":"Brasilia",
                "team_left":"Colombia",
		"team_right":"Costa de Marfil"
            },
            {
                "id":"4",
                "date":"2014-06-19T19:00:00-03:00",
                "place":"Natal",
                "team_left":"Japon",
		"team_right":"Grecia"
            },
            {
                "id":"5",
                "date":"2014-06-24T17:00:00-03:00",
                "place":"Cuiaba",
                "team_left":"Japon",
		"team_right":"Colombia"
            },
            {
                "id":"6",
                "date":"2014-06-24T17:00:00-03:00",
                "place":"Fortaleza",
                "team_left":"Grecia",
		"team_right":"Costa de Marfil"
            }     				
         ]
       },
       {
         "id" : "D",
         "match":[
            {
                "id":"1",
                "date":"2014-06-14T16:00:00-03:00",
                "place":"Fortaleza",
                "team_left":"Uruguay",
		"team_right":"Costa Rica"
            },
            {
                "id":"2",
                "date":"2014-06-14T18:00:00-03:00",
                "place":"Manaos",
                "team_left":"Inglaterra",
		"team_right":"Italia"
            },
            {
                "id":"3",
                "date":"2014-06-19T16:00:00-03:00",
                "place":"Sao Paulo",
                "team_left":"Uruguay",
		"team_right":"Inglaterra"
            },
            {
                "id":"4",
                "date":"2014-06-20T13:00:00-03:00",
                "place":"Recife",
                "team_left":"Italia",
		"team_right":"Costa Rica"
            },
            {
                "id":"5",
                "date":"2014-06-24T13:00:00-03:00",
                "place":"Natal",
                "team_left":"Italia",
		"team_right":"Uruguay"
            },
            {
                "id":"6",
                "date":"2014-06-24T13:00:00-03:00",
                "place":"Belo Horizonte",
                "team_left":"Costa Rica",
		"team_right":"Inglaterra"
            }     				
         ]
        },
        {
         "id" : "E",
         "match":[
            {
                "id":"1",
                "date":"2014-06-15T13:00:00-03:00",
                "place":"Brasilia",
                "team_left":"Suiza",
		"team_right":"Ecuador"
            },
            {
                "id":"2",
                "date":"2014-06-15T16:00:00-03:00",
                "place":"Porto Alegre",
                "team_left":"Francia",
		"team_right":"Honduras"
            },
            {
                "id":"3",
                "date":"2014-06-20T16:00:00-03:00",
                "place":"Bahia",
                "team_left":"Suiza",
		"team_right":"Francia"
            },
            {
                "id":"4",
                "date":"2014-06-20T19:00:00-03:00",
                "place":"Curitiba",
                "team_left":"Honduras",
		"team_right":"Ecuador"
            },
            {
                "id":"5",
                "date":"2014-06-25T17:00:00-03:00",
                "place":"Manaos",
                "team_left":"Honduras",
		"team_right":"Suiza"
            },
            {
                "id":"6",
                "date":"2014-06-25T17:00:00-03:00",
                "place":"Rio de Janeiro",
                "team_left":"Ecuador",
		"team_right":"Francia"
            }     				
         ]
        },
        {
         "id" : "F",
         "match":[
            {
                "id":"1",
                "date":"2014-06-15T19:00:00-03:00",
                "place":"Rio de Janeiro",
                "team_left":"Argentina",
		"team_right":"Bosnia"
            },
            {
                "id":"2",
                "date":"2014-06-16T16:00:00-03:00",
                "place":"Curitiba",
                "team_left":"Iran",
		"team_right":"Nigeria"
            },
            {
                "id":"3",
                "date":"2014-06-21T13:00:00-03:00",
                "place":"Belo Horizonte",
                "team_left":"Argentina",
		"team_right":"Iran"
            },
            {
                "id":"4",
                "date":"2014-06-21T19:00:00-03:00",
                "place":"Cuiaba",
                "team_left":"Nigeria",
		"team_right":"Bosnia"
            },
            {
                "id":"5",
                "date":"2014-06-25T13:00:00-03:00",
                "place":"Porto Alegre",
                "team_left":"Nigeria",
		"team_right":"Argentina"
            },
            {
                "id":"6",
                "date":"2014-06-25T13:00:00-03:00",
                "place":"Bahia",
                "team_left":"Bosnia",
		"team_right":"Iran"
            }     				
         ]
        },
       {
         "id" : "G",
         "match":[
            {
                "id":"1",
                "date":"2014-06-16T13:00:00-03:00",
                "place":"Bahia",
                "team_left":"Alemania",
		"team_right":"Portugal"
            },
            {
                "id":"2",
                "date":"2014-06-16T19:00:00-03:00",
                "place":"Natal",
                "team_left":"Ghana",
		"team_right":"USA"
            },
            {
                "id":"3",
                "date":"2014-06-21T16:00:00-03:00",
                "place":"Fortaleza",
                "team_left":"Alemania",
		"team_right":"Ghana"
            },
            {
                "id":"4",
                "date":"2014-06-22T16:00:00-03:00",
                "place":"Manaos",
                "team_left":"USA",
		"team_right":"Portugal"
            },
            {
                "id":"5",
                "date":"2014-06-26T13:00:00-03:00",
                "place":"Recife",
                "team_left":"USA",
		"team_right":"Alemania"
            },
            {
                "id":"6",
                "date":"2014-06-26T13:00:00-03:00",
                "place":"Brasilia",
                "team_left":"Portugal",
		"team_right":"Ghana"
            }     				
         ]
       },
       {
         "id" : "H",
         "match":[
            {
                "id":"1",
                "date":"2014-06-17T13:00:00-03:00",
                "place":"Belo Horizonte",
                "team_left":"Belgica",
		"team_right":"Argelia"
            },
            {
                "id":"2",
                "date":"2014-06-17T19:00:00-03:00",
                "place":"Cuiaba",
                "team_left":"Rusia",
		"team_right":"Corea del Sur"
            },
            {
                "id":"3",
                "date":"2014-06-22T13:00:00-03:00",
                "place":"Porto Alegre",
                "team_left":"Corea del Sur",
		"team_right":"Argelia"
            },
            {
                "id":"4",
                "date":"2014-06-22T19:00:00-03:00",
                "place":"Rio de Janeiro",
                "team_left":"Belgica",
		"team_right":"Rusia"
            },
            {
                "id":"5",
                "date":"2014-06-26T17:00:00-03:00",
                "place":"Sao Paulo",
                "team_left":"Corea del Sur",
		"team_right":"Belgica"
            },
            {
                "id":"6",
                "date":"2014-06-26T17:00:00-03:00",
                "place":"Curitiba",
                "team_left":"Argelia",
		"team_right":"Rusia"
            }     				
         ]
       }
    ]
};
