<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
        <title>Ejemplo de PHP y MySQL - Login</title>
        <link href="css/estilo.css" type="text/css" rel="stylesheet">
    </head>
    <body>
        <div class="titulo">
            <h1>Acceso a sus Contactos</h1>
        </div>
        <div class="login">
            <form id="login" method="post" action="./login">
                <div>
                    <span class="labelLogin">Usuario:</span>
                    <input name="username" type="text" tabindex="0" class="textLogin"/>
                </div>
                <div>
                    <span class="labelLogin">Clave:</span>
                    <input name="password" type="password" tabindex="0" class="textLogin"/>
                </div>
                <div class="error">
                    <span><?php echo getErrorLogin(); ?></span>
                </div>
                <div align="center">
                    <input type="submit" tabindex="0" class="loginButton" value="Acceder"/>
                </div>
                <div align="center">
                    <a href="./">Inicio</a>
                </div>
            </form>
        </div>
    </body>
</html>