<!doctype html>

<html lang="en">
<head>

    <title>Copa Mundial 2014</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" href="images/icon.ico"/>
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="css/bootstrap-theme.min.css">

    <!-- Pick a theme, load the plugin & initialize plugin -->
    <link href="css/theme.default.css" rel="stylesheet">
    <link href="css/jquery.qtip.min.css" rel="stylesheet">
  
    <link id="user_style" rel="stylesheet" type="text/css" href="css/style.css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

  <!-- Scripts -->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet" type="text/css" href="css/jquery-ui.min.css">
  
  <script src="js/jquery.js" type="text/javascript"></script>
  <script src="js/cookies.js" type="text/javascript"></script>
  <script src="js/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>
  <script src="js/jquery.qtip.min.js" type="text/javascript"></script>
  <script src="js/bootstrap.min.js" type="text/javascript"></script>
  <script src="js/jquery.tablesorter.min.js"></script>
  <script src="js/jquery.tablesorter.widgets.min.js"></script>
  <script src="js/fixture.js" type="text/javascript"></script>
  <script src="js/script.js" type="text/javascript"></script>
  
</head>

<body>	

  <!--Seccion de Navegacion-->
  <nav role="navigation" class="navbar  my-nav">
      <div class="">
        <div class="row">
          <div class="col-md-12">
            <div class="col-md-6">
              <a href="./"><img src="images/titulo.png" alt=""></a>                
            </div>      
            <div class="col-md-6">
              <div id="navbarCollapse" class="collapse navbar-collapse">
                  <ul id="my-navbar" class="nav navbar-nav navbar-right my-navbar">
                      <li><a class="active" href="./"><span class="fa fa-home"> Inicio</span></a></li>
                      <li><a onclick=" changeTheme();" href="#"><span class="fa fa-edit"> Estilo</span></a></li>
                      <li><a onclick="contact()" href="#"><span class="fa fa-barcode"> Contacto</span></a></li>
                      <li><a href="./readme"><span class="fa fa-file-text-o"> Readme</span></a></li>
                      <li><a href="./como_jugar"><span class="fa fa-question"> Cómo Jugar</span></a></li>
                  </ul>
              </div>  
            </div> 
          </div>
        </div>  
      </div>
  </nav>

  <!--Seccion de Grupos-->
  <div class="botones">
    <div class="row ">
        <div class="col-md-3 pull-right">
                <?php printUserData(); ?>
        </div>
    </div>
  </div>
  
  <div id="dialogo" title="Datos Autores">
    <p>Autores:<br/><br/> - Brian Magario  LU:89658<br/> <br/> - Magin Suarez  LU:85429 </p>
  </div>

  <div id="main">
      <div class="container my-container">
      Aqui va el contenido cuando no esta logueado.
      </div>
  </div>


    <!--Seccion de Footer-->
	<footer class="footer my-nav">
		© 2014 Brian E. Magario - Alberto M. Suarez. All rights reserved.         
	</footer>

</body>
</html>