<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
        <title>Ejemplo de PHP y MySQL - Subir Foto</title>
        <link href="css/estilo.css" type="text/css" rel="stylesheet">
    </head>
    <body>
        <div class="titulo">
            <h1>Seleccione la Foto a Subir</h1>
        </div>
    <center>
        <form class="upload" action="./uploadFile" method="post" enctype="multipart/form-data">
            <label for="file">Foto:</label>
            <input type="hidden" name="mail" value='<?php echo $_GET['mail']; ?>' />
            <input type="file" name="file" id="file" />
            <br />
            <input type="submit" name="submit" value="Aceptar" />
        </form>
        <div class="footer">
            <a href="./">Volver</a>
        </div>
    </center>
</body>
</html>
