<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
        <title>Ejemplo de PHP y MySQL - Subir Foto</title>
        <link href="css/estilo.css" type="text/css" rel="stylesheet">
    </head>
    <body>
    <div class="titulo">
    	<h1>Error al subir la Foto</h1>
    </div>
    
    <center>
    <div class="error">
        <span><?php echo getErrorUpload();?></span>
    </div>
	<div class="footer">
		<a href="./">Volver</a>
	</div>
    </center>
    </body>
</html>
